import { Photo, Video } from "./types";

export const INITIAL_PHOTOS: Photo[] = [
  { id: "p1", url: "https://ducphuongmedical.com/hinhanh/XuatKhau/poster6.jpg", title: "Nông sản TAJERMY 1" },
  { id: "p2", url: "https://ducphuongmedical.com/hinhanh/XuatKhau/tonghop.jpg", title: "Nông sản TAJERMY 2" },
  { id: "p3", url: "https://ducphuongmedical.com/hinhanh/XuatKhau/hatdieu.jpg", title: "Nông sản TAJERMY 3" },
  { id: "p4", url: "https://ducphuongmedical.com/hinhanh/XuatKhau/chanh.jpg", title: "Nông sản TAJERMY 4" },
  { id: "p5", url: "https://ducphuongmedical.com/hinhanh/XuatKhau/cafe.jpg", title: "Nông sản TAJERMY 5" },
  { id: "p6", url: "https://ducphuongmedical.com/hinhanh/XuatKhau/poster7.jpg", title: "Nông sản TAJERMY 6" },
  { id: "p7", url: "https://ducphuongmedical.com/hinhanh/XuatKhau/poster1.jpg", title: "Nông sản TAJERMY 7" },
  { id: "p8", url: "https://ducphuongmedical.com/hinhanh/XuatKhau/poster3.jpg", title: "Nông sản TAJERMY 8" },
  { id: "p9", url: "https://ducphuongmedical.com/hinhanh/XuatKhau/poster4.jpg", title: "Nông sản TAJERMY 9" },
  { id: "p10", url: "https://ducphuongmedical.com/hinhanh/XuatKhau/poster5.jpg", title: "Nông sản TAJERMY 10" },
  { id: "p11", url: "https://ducphuongmedical.com/hinhanh/XuatKhau/poster8.jpg", title: "Nông sản TAJERMY 11" },
  { id: "p12", url: "https://ducphuongmedical.com/hinhanh/Chanh/Hinh/12.jpg", title: "Nông sản TAJERMY 12" },
  { id: "p13", url: "https://ducphuongmedical.com/hinhanh/Chanh/Hinh/13.jpg", title: "Nông sản TAJERMY 13" },
  { id: "p14", url: "https://ducphuongmedical.com/hinhanh/Chanh/Hinh/14.jpg", title: "Nông sản TAJERMY 14" },
  { id: "p15", url: "https://ducphuongmedical.com/hinhanh/Chanh/Hinh/15.jpg", title: "Nông sản TAJERMY 15" },
  { id: "p16", url: "https://ducphuongmedical.com/hinhanh/Chanh/Hinh/16.jpg", title: "Nông sản TAJERMY 16" },
  { id: "p17", url: "https://ducphuongmedical.com/hinhanh/Chanh/Hinh/17.jpg", title: "Nông sản TAJERMY 17" },
  { id: "p18", url: "https://ducphuongmedical.com/hinhanh/Chanh/Hinh/18.jpg", title: "Nông sản TAJERMY 18" },
  { id: "p19", url: "https://ducphuongmedical.com/hinhanh/Chanh/Hinh/19.jpg", title: "Nông sản TAJERMY 19" },
  { id: "p20", url: "https://ducphuongmedical.com/hinhanh/Chanh/Hinh/20.jpg", title: "Nông sản TAJERMY 20" },
  { id: "p21", url: "https://ducphuongmedical.com/hinhanh/Chanh/Hinh/21.jpg", title: "Nông sản TAJERMY 21" },
  { id: "p22", url: "https://ducphuongmedical.com/hinhanh/Chanh/Hinh/22.jpg", title: "Nông sản TAJERMY 22" },
  { id: "p23", url: "https://ducphuongmedical.com/hinhanh/Chanh/Hinh/23.jpg", title: "Nông sản TAJERMY 23" },
  { id: "p24", url: "https://ducphuongmedical.com/hinhanh/Chanh/Hinh/24.jpg", title: "Nông sản TAJERMY 24" },
  { id: "p25", url: "https://ducphuongmedical.com/hinhanh/Chanh/Hinh/25.jpg", title: "Nông sản TAJERMY 25" },
  { id: "p26", url: "https://ducphuongmedical.com/hinhanh/Chanh/Hinh/26.jpg", title: "Nông sản TAJERMY 26" },
  { id: "p27", url: "https://ducphuongmedical.com/hinhanh/Chanh/Hinh/27.jpg", title: "Nông sản TAJERMY 27" },
  { id: "p28", url: "https://ducphuongmedical.com/hinhanh/Chanh/Hinh/28.jpg", title: "Nông sản TAJERMY 28" },
];

export const INITIAL_VIDEOS: Video[] = [
  { id: "v1", url: "https://www.youtube.com/watch?v=xuSoneXQDs8", thumbnail: "https://img.youtube.com/vi/xuSoneXQDs8/hqdefault.jpg", title: "Quy trình sản xuất 1" },
  { id: "v2", url: "https://www.youtube.com/watch?v=W4-wu2M_XPM", thumbnail: "https://img.youtube.com/vi/W4-wu2M_XPM/hqdefault.jpg", title: "Quy trình sản xuất 2" },
  { id: "v3", url: "https://www.youtube.com/watch?v=P3VVmn3vQvA", thumbnail: "https://img.youtube.com/vi/P3VVmn3vQvA/hqdefault.jpg", title: "Quy trình sản xuất 3" },
  { id: "v4", url: "https://www.youtube.com/watch?v=sMj5HvH1Mws", thumbnail: "https://img.youtube.com/vi/sMj5HvH1Mws/hqdefault.jpg", title: "Quy trình sản xuất 4" },
  { id: "v5", url: "https://www.youtube.com/watch?v=8e6SYZxk9Zk", thumbnail: "https://img.youtube.com/vi/8e6SYZxk9Zk/hqdefault.jpg", title: "Quy trình sản xuất 5" },
  { id: "v6", url: "https://www.youtube.com/watch?v=kwm7YRxPjLU", thumbnail: "https://img.youtube.com/vi/kwm7YRxPjLU/hqdefault.jpg", title: "Quy trình sản xuất 6" },
];
